spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankroll_management?serverTimezone=UTC
    username: root
    password: Tmvmffotlvi
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

spring.thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8

jwt:
  secret: SECRET

